trigger:
  - main

pool:
  -vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: buildmaven
        steps:
          - task: Maven@3
            inputs:
               mavenPomFile: 'pom.xml'
               jdkVersionOption: 1.8
               publishJUnitResults: true
               goals: package
              
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
    

